import React from "react";

interface BadgeProps {
  children: React.ReactNode;
  variant?:
    | "success"
    | "warning"
    | "danger"
    | "high"
    | "info"
    | "neutral"
    | "destructive"
    | "default"
    | "outline"
    | "secondary";
  className?: string;
  icon?: React.ElementType;
}

export const Badge: React.FC<BadgeProps> = ({
  children,
  variant = "neutral",
  className = "",
  icon: Icon,
}) => {
  /**
   * WHY: `shadow-sm` is applied once in the base className below, so variant
   * strings no longer duplicate it. Previously success/warning/danger/high/info
   * all included `shadow-sm` redundantly — Tailwind merged them correctly but
   * it was misleading noise in every variant definition.
   */
  /**
   * WCAG 1.4.3 (Contrast Minimum, zero-tolerance contrast rule):
   * neutral/default/secondary/outline previously hard-coded `text-slate-700`
   * against `bg-secondary` / a transparent (page/card) background with no
   * `dark:` override. `--secondary` and `--background`/`--card` invert in
   * dark mode (plugin/src/index.css `.dark` block) but slate-700 does not,
   * producing dark text on a dark fill — measured 1.54:1 (neutral, against
   * `--secondary` dark) and 1.65:1 (outline, against `--card` dark), both
   * far below the 4.5:1 floor. Fixed by swapping to the semantic tokens
   * these surfaces already define for exactly this pairing:
   * `text-secondary-foreground` (paired with `bg-secondary`, defined in
   * both `:root` and `.dark`) and `text-foreground` (the general-purpose
   * text token, correct against both `--background` and `--card` in both
   * themes) — no new colors, both already generated by `@theme inline`.
   * Re-verified light mode stays unaffected (was already >=6.87:1) and both
   * tokens land at 9-14:1 in the failing dark pairs. `atoms/Badge.tsx`
   * (a separate, unrelated Badge component) already uses this exact
   * `text-secondary-foreground` / `text-foreground` pattern — this brings
   * `ui/Badge.tsx` in line with it, not a new convention.
   */
  const variants: Record<NonNullable<BadgeProps["variant"]>, string> = {
    success: "bg-emerald-50 text-emerald-700 border-emerald-200",
    warning: "bg-amber-50 text-amber-700 border-amber-200",
    danger: "bg-red-50 text-red-700 border-red-200",
    high: "bg-orange-50 text-orange-700 border-orange-200",
    info: "bg-blue-50 text-blue-700 border-blue-200",
    neutral: "bg-secondary text-secondary-foreground border-border",
    // Aliases for compatibility
    destructive: "bg-red-50 text-red-700 border-red-200",
    default: "bg-secondary text-secondary-foreground border-border",
    secondary: "bg-secondary text-secondary-foreground border-border",
    outline: "bg-transparent border border-border text-foreground",
  };

  return (
    <span
      className={`inline-flex items-center rounded-full border px-4 py-1.5 text-xs font-black tracking-[0.1em] uppercase shadow-sm ${variants[variant]} ${className}`}
    >
      {/*
        WCAG 4.1.2 / decorative-icon rule: every current call site
        (for example SelfCheckPanel.tsx's StatusBadge) pairs the icon with
        adjacent Badge text that already carries the full meaning — the
        icon has no independent
        label of its own. aria-hidden keeps NVDA/JAWS/VoiceOver from
        announcing a redundant "image" role on top of the text (matches
        Button.tsx's icon pattern, ui/Button.tsx lines ~48-52).
      */}
      {Icon && <Icon size={12} className="mr-1.5" aria-hidden="true" />}
      {children}
    </span>
  );
};
